### PR TITLE
CMake fixes + OS X time support + Pendant IP config

### PR DESCRIPTION
**Pull request by ahundt**

### CODE REVIEW

**Comment by ahundt** [comment]
@SalvoVirga I just added the ability to change IP addresses at runtime.

**Comment by SalvoVirga** [comment]
I will probably take the first two commits, but not the IP config thingie. That is already solve in the development branch, although not using the Process Data. We will probably discuss that option and see what is better.

**Comment by marcoesposito1988** [comment]
@ahundt, thank you for the contribution!

The CMake and the OS X compatibility fixes look good, and we would like to merge them.

The IP address thingy actually is something completely different and would deserve its own pull request. However, since we implemented automatic IP detection in the development branch and a configuration via file in the Sunrise project for other matters, we would not take the change. Since you are an advanced user and can deal with rough edges in code, we encourage you to take a look at the development branch first.

So if you could change the pull request to only include the first two commits, we could directly merge it; otherwise you can create a new one, or we can copy-paste the changes if you don't have time.

As a final remark, to minimize round trips in future communication, I would ask you to stick to our coding style in your proposed changes. The one you used in this pull request was very different.

**Comment by ahundt** [comment]
feel free to copy paste the code, sorry about the coding style issues. I'm a bit short on time at the moment

I'm sure they are present in both C++ and Java. Much of the code I modified is just existing code blobs I put in (I provided references in the source itself where appropriate) so in some spots I didn't modify it.

**Comment by SalvoVirga** [comment]
I added the cmake fixes in #69 manually.  For the config parameters we solved making our own configuration text file, using the KUKA process data thingie is not a bad idea, but I would be yet another file to copy/paste in the right place, we are still discussing about that from time to time.

**Pull request closed without merging**
